### ISSUE TITLE
Culd not find class problem

### ISSUE THREAD

**Issue by AlexDovgan** [gueei/AndroidBinding#10]
Hi,

I tryed to use your library in my project, and all was fine. But when i sturt to use BindableLinearLayout I give the next runtime  errors:

10-21 15:27:31.111: W/dalvikvm(15077): Link of class 'Lgueei/binding/v30/viewAttributes/absListView/MultiChoiceMode;' failed
10-21 15:27:31.111: E/dalvikvm(15077): Could not find class 'gueei.binding.v30.viewAttributes.absListView.MultiChoiceMode', referenced from method gueei.binding.v30.bindingProviders.ListViewProviderV30.createAttributeForView
10-21 15:27:31.121: W/dalvikvm(15077): VFY: unable to resolve new-instance 648 (Lgueei/binding/v30/viewAttributes/absListView/MultiChoiceMode;) in Lgueei/binding/v30/bindingProviders/ListViewProviderV30;
10-21 15:27:31.121: W/dalvikvm(15077): Link of class 'Lgueei/binding/v30/viewAttributes/absListView/ModalCheckedItemPositions;' failed
10-21 15:27:31.121: E/dalvikvm(15077): Could not find class 'gueei.binding.v30.viewAttributes.absListView.ModalCheckedItemPositions', referenced from method gueei.binding.v30.bindingProviders.ListViewProviderV30.createAttributeForView
10-21 15:27:31.121: W/dalvikvm(15077): VFY: unable to resolve new-instance 645 (Lgueei/binding/v30/viewAttributes/absListView/ModalCheckedItemPositions;) in Lgueei/binding/v30/bindingProviders/ListViewProviderV30;
10-21 15:27:31.121: W/dalvikvm(15077): Link of class 'Lgueei/binding/v30/viewAttributes/OnAttachViewAttributeV30;' failed
10-21 15:27:31.121: E/dalvikvm(15077): Could not find class 'gueei.binding.v30.viewAttributes.OnAttachViewAttributeV30', referenced from method gueei.binding.v30.bindingProviders.ViewProviderV30.createAttributeForView
10-21 15:27:31.121: W/dalvikvm(15077): VFY: unable to resolve new-instance 641 (Lgueei/binding/v30/viewAttributes/OnAttachViewAttributeV30;) in Lgueei/binding/v30/bindingProviders/ViewProviderV30;
10-21 15:27:31.121: W/dalvikvm(15077): Link of class 'Lgueei/binding/v30/viewAttributes/OnDetachViewAttributeV30;' failed
10-21 15:27:31.121: E/dalvikvm(15077): Could not find class 'gueei.binding.v30.viewAttributes.OnDetachViewAttributeV30', referenced from method gueei.binding.v30.bindingProviders.ViewProviderV30.createAttributeForView
10-21 15:27:31.121: W/dalvikvm(15077): VFY: unable to resolve new-instance 642 (Lgueei/binding/v30/viewAttributes/OnDetachViewAttributeV30;) in Lgueei/binding/v30/bindingProviders/ViewProviderV30;
10-21 15:27:31.141: W/dalvikvm(15077): VFY: unable to resolve virtual method 3874: Lgueei/binding/v30/app/BindingActivityV30;.getActionBar ()Landroid/app/ActionBar;
10-21 15:27:31.161: W/dalvikvm(15077): VFY: unable to resolve virtual method 3879: Lgueei/binding/v30/app/BindingActivityV30;.invalidateOptionsMenu ()V
10-21 15:27:31.171: W/dalvikvm(15077): threadid=1: thread exiting with uncaught exception (group=0x40020ac0)
10-21 15:27:31.181: E/AndroidRuntime(15077): FATAL EXCEPTION: main
10-21 15:27:31.181: E/AndroidRuntime(15077): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alexdov.carprods/com.alexdov.carprods.MainActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class binding.BindableLinearLayout
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2663)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.app.ActivityThread.access$2300(ActivityThread.java:125)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.os.Handler.dispatchMessage(Handler.java:99)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.os.Looper.loop(Looper.java:123)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.app.ActivityThread.main(ActivityThread.java:4627)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at java.lang.reflect.Method.invokeNative(Native Method)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at java.lang.reflect.Method.invoke(Method.java:521)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at dalvik.system.NativeStart.main(Native Method)
10-21 15:27:31.181: E/AndroidRuntime(15077): Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class binding.BindableLinearLayout
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:576)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:618)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.view.LayoutInflater.inflate(LayoutInflater.java:407)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:198)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.app.Activity.setContentView(Activity.java:1647)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at com.alexdov.carprods.MainActivity.onCreate(MainActivity.java:14)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
10-21 15:27:31.181: E/AndroidRuntime(15077):    ... 11 more
10-21 15:27:31.181: E/AndroidRuntime(15077): Caused by: java.lang.ClassNotFoundException: binding.BindableLinearLayout in loader dalvik.system.PathClassLoader[/data/app/com.alexdov.carprods-2.apk]
10-21 15:27:31.181: E/AndroidRuntime(15077):    at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:243)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at java.lang.ClassLoader.loadClass(ClassLoader.java:532)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.view.LayoutInflater.createView(LayoutInflater.java:466)
10-21 15:27:31.181: E/AndroidRuntime(15077):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:565)
10-21 15:27:31.181: E/AndroidRuntime(15077):    ... 20 more
Can you help me?
Regards Alexey Dovgan.

**Comment by gueei** [comment]
Hi,
Which Android version you are targeting?
